/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_products__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Login */
        post: operations["admin_login_auth_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_me_patch"];
        trace?: never;
    };
    "/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Addresses */
        get: operations["list_addresses_me_addresses_get"];
        put?: never;
        /** Create Address */
        post: operations["create_address_me_addresses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/addresses/{address_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Address */
        delete: operations["delete_address_me_addresses__address_id__delete"];
        options?: never;
        head?: never;
        /** Update Address */
        patch: operations["update_address_me_addresses__address_id__patch"];
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cart */
        get: operations["get_cart_cart_get"];
        put?: never;
        post?: never;
        /** Clear Cart */
        delete: operations["clear_cart_cart_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_cart_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_cart_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_cart_items__item_id__patch"];
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_orders__order_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_admin_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{order_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_admin_orders__order_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{order_code}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Order Status */
        patch: operations["update_order_status_admin_orders__order_code__status_patch"];
        trace?: never;
    };
    "/admin/custom-scent-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Custom Scent */
        get: operations["list_custom_scent_admin_custom_scent_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/custom-scent-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Custom Scent */
        patch: operations["review_custom_scent_admin_custom_scent_requests__request_id__patch"];
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_admin_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_admin_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_admin_products__product_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Product
         * @description Ẩn sản phẩm (is_active = false), không xóa khỏi DB.
         */
        delete: operations["delete_product_admin_products__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_admin_products__product_id__patch"];
        trace?: never;
    };
    "/admin/products/{product_id}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Components */
        put: operations["replace_components_admin_products__product_id__components_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{product_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Variant */
        post: operations["add_variant_admin_products__product_id__variants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Variant */
        patch: operations["update_variant_admin_variants__variant_id__patch"];
        trace?: never;
    };
    "/admin/scents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scents */
        get: operations["list_scents_admin_scents_get"];
        put?: never;
        /** Create Scent */
        post: operations["create_scent_admin_scents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/scents/{scent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Scent */
        patch: operations["update_scent_admin_scents__scent_id__patch"];
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressIn */
        AddressIn: {
            /** Recipient Name */
            recipient_name: string;
            /** Phone */
            phone: string;
            /** Province */
            province: string;
            /** District */
            district?: string | null;
            /** Ward */
            ward: string;
            /** Address Line */
            address_line: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** AddressOut */
        AddressOut: {
            /** Id */
            id: number;
            /** Recipient Name */
            recipient_name: string;
            /** Phone */
            phone: string;
            /** Province */
            province: string;
            /** District */
            district: string | null;
            /** Ward */
            ward: string;
            /** Address Line */
            address_line: string;
            /** Is Default */
            is_default: boolean;
        };
        /** AddressUpdate */
        AddressUpdate: {
            /** Recipient Name */
            recipient_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Province */
            province?: string | null;
            /** District */
            district?: string | null;
            /** Ward */
            ward?: string | null;
            /** Address Line */
            address_line?: string | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /** AdminCustomScentListItem */
        AdminCustomScentListItem: {
            /** Id */
            id: number;
            /** Order Code */
            order_code: string;
            /** Order Status */
            order_status: string;
            /** Recipient Name */
            recipient_name: string;
            /** Phone */
            phone: string;
            /** Description */
            description: string;
            /** Requested Text */
            requested_text: string;
            /** Status */
            status: string;
            /** Internal Note */
            internal_note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed At */
            reviewed_at: string | null;
        };
        /** AdminCustomScentOut */
        AdminCustomScentOut: {
            /** Id */
            id: number;
            /** Order Item Id */
            order_item_id: number;
            /** Description */
            description: string;
            /** Requested Text */
            requested_text: string;
            /** Status */
            status: string;
            /** Internal Note */
            internal_note: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
        };
        /** AdminCustomer */
        AdminCustomer: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
        };
        /** AdminLoginIn */
        AdminLoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** AdminOrderDetail */
        AdminOrderDetail: {
            /** Order Code */
            order_code: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Subtotal */
            subtotal: number;
            /** Shipping Fee */
            shipping_fee: number;
            /** Total */
            total: number;
            /** Note */
            note: string | null;
            customer: components["schemas"]["AdminCustomer"];
            shipping: components["schemas"]["ShippingSnapshot"];
            /** Payments */
            payments: components["schemas"]["AdminPaymentOut"][];
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEntry"][];
            /** Custom Scent Requests */
            custom_scent_requests: components["schemas"]["AdminCustomScentOut"][];
        };
        /** AdminOrderListItem */
        AdminOrderListItem: {
            /** Order Code */
            order_code: string;
            /** Status */
            status: string;
            /** Recipient Name */
            recipient_name: string;
            /** Phone */
            phone: string;
            /** Payment Method */
            payment_method: string | null;
            /** Payment Status */
            payment_status: string | null;
            /** Total */
            total: number;
            /** Item Count */
            item_count: number;
            /** Pending Custom Scents */
            pending_custom_scents: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminOrderPage */
        AdminOrderPage: {
            /** Items */
            items: components["schemas"]["AdminOrderListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** AdminPaymentOut */
        AdminPaymentOut: {
            /** Id */
            id: number;
            /** Method */
            method: string;
            /** Status */
            status: string;
            /** Amount */
            amount: number;
            /** Paid At */
            paid_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminProductOut */
        AdminProductOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Product Type */
            product_type: string;
            /** Description */
            description: string;
            /** Story */
            story: string | null;
            /** Image Url */
            image_url: string | null;
            /** Burn Time */
            burn_time: string | null;
            /** Ingredients */
            ingredients: string | null;
            /** Featured */
            featured: boolean;
            /** Allow Custom Scent */
            allow_custom_scent: boolean;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Variants */
            variants: components["schemas"]["AdminVariantOut"][];
            /** Components */
            components: components["schemas"]["ComboComponentOut"][];
        };
        /** AdminScentOut */
        AdminScentOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name Vi */
            name_vi: string;
            /** Name En */
            name_en: string;
            /** Description */
            description: string | null;
            /** Notes */
            notes: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** AdminVariantOut */
        AdminVariantOut: {
            /** Id */
            id: number;
            /** Product Id */
            product_id: number;
            /** Size Ml */
            size_ml: number | null;
            /** Label */
            label: string;
            /** Price */
            price: number;
            /** Stock Quantity */
            stock_quantity: number;
            /** Is Active */
            is_active: boolean;
            scent: components["schemas"]["ScentOut"] | null;
        };
        /** CartItemIn */
        CartItemIn: {
            /** Product Id */
            product_id: number;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Variant Id */
            variant_id?: number | null;
            /** Size Ml */
            size_ml?: number | null;
            /** Custom Scent Text */
            custom_scent_text?: string | null;
            /** Selections */
            selections?: components["schemas"]["SelectionIn"][] | null;
        };
        /** CartItemOut */
        CartItemOut: {
            /** Id */
            id: number;
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Product Type */
            product_type: string;
            /** Image Url */
            image_url: string | null;
            /** Variant Id */
            variant_id: number | null;
            /** Label */
            label: string;
            /** Size Ml */
            size_ml: number | null;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number;
            /** Line Total */
            line_total: number;
            /** Custom Scent Text */
            custom_scent_text: string | null;
            /** Selections */
            selections: components["schemas"]["app__schemas__cart__SelectionOut"][];
            /** Stock Available */
            stock_available: number | null;
            /** Low Stock */
            low_stock: boolean;
            /** Is Out Of Stock */
            is_out_of_stock: boolean;
            /** Has Stock Issue */
            has_stock_issue: boolean;
            /** Issues */
            issues: components["schemas"]["StockIssue"][];
        };
        /** CartItemUpdate */
        CartItemUpdate: {
            /** Quantity */
            quantity: number;
        };
        /** CartOut */
        CartOut: {
            /** Items */
            items: components["schemas"]["CartItemOut"][];
            /** Subtotal */
            subtotal: number;
            /** Item Count */
            item_count: number;
            /** Has Stock Issue */
            has_stock_issue: boolean;
            /** Can Checkout */
            can_checkout: boolean;
        };
        /** ComboComponentOut */
        ComboComponentOut: {
            /** Component Type */
            component_type: string;
            /** Size Ml */
            size_ml: number | null;
            /** Quantity */
            quantity: number;
        };
        /** ComponentIn */
        ComponentIn: {
            /**
             * Component Type
             * @enum {string}
             */
            component_type: "CANDLE" | "CARD";
            /** Size Ml */
            size_ml?: number | null;
            /** Quantity */
            quantity: number;
        };
        /** CustomScentRequestOut */
        CustomScentRequestOut: {
            /** Id */
            id: number;
            /** Order Item Id */
            order_item_id: number;
            /** Description */
            description: string;
            /** Requested Text */
            requested_text: string;
            /** Status */
            status: string;
        };
        /** CustomScentReviewIn */
        CustomScentReviewIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "ACCEPTED" | "REJECTED";
            /** Internal Note */
            internal_note?: string | null;
        };
        /** DailyStat */
        DailyStat: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Orders */
            orders: number;
            /** Revenue */
            revenue: number;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Total Orders */
            total_orders: number;
            /** Cancelled Orders */
            cancelled_orders: number;
            /** Total Revenue */
            total_revenue: number;
            /** Orders Pending */
            orders_pending: number;
            /** Orders Confirmed */
            orders_confirmed: number;
            /** Orders Preparing */
            orders_preparing: number;
            /** Orders Shipped */
            orders_shipped: number;
            /** Orders Completed */
            orders_completed: number;
            /** Pending Custom Scents */
            pending_custom_scents: number;
            /** Out Of Stock Count */
            out_of_stock_count: number;
            /** Low Stock Threshold */
            low_stock_threshold: number;
            /** Low Stock */
            low_stock: components["schemas"]["LowStockItem"][];
            /** Period Days */
            period_days: number;
            /** Period Revenue */
            period_revenue: number;
            /** Daily */
            daily: components["schemas"]["DailyStat"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LowStockItem */
        LowStockItem: {
            /** Variant Id */
            variant_id: number;
            /** Product Name */
            product_name: string;
            /** Label */
            label: string;
            /** Stock Quantity */
            stock_quantity: number;
        };
        /** OrderCreateIn */
        OrderCreateIn: {
            /** Address Id */
            address_id: number;
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "PAYOS" | "COD";
            /** Note */
            note?: string | null;
        };
        /** OrderDetail */
        OrderDetail: {
            /** Order Code */
            order_code: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Subtotal */
            subtotal: number;
            /** Shipping Fee */
            shipping_fee: number;
            /** Total */
            total: number;
            /** Note */
            note: string | null;
            shipping: components["schemas"]["ShippingSnapshot"];
            payment: components["schemas"]["PaymentOut"] | null;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEntry"][];
            /** Custom Scent Requests */
            custom_scent_requests: components["schemas"]["CustomScentRequestOut"][];
        };
        /** OrderItemOut */
        OrderItemOut: {
            /** Id */
            id: number;
            /** Product Type */
            product_type: string;
            /** Product Name */
            product_name: string;
            /** Variant Label */
            variant_label: string;
            /** Size Ml */
            size_ml: number | null;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number;
            /** Line Total */
            line_total: number;
            /** Custom Scent Text */
            custom_scent_text: string | null;
            /** Selections */
            selections: components["schemas"]["app__schemas__order__SelectionOut"][];
        };
        /** OrderListItem */
        OrderListItem: {
            /** Order Code */
            order_code: string;
            /** Status */
            status: string;
            /** Payment Method */
            payment_method: string | null;
            /** Payment Status */
            payment_status: string | null;
            /** Total */
            total: number;
            /** Item Count */
            item_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrderStatusUpdateIn */
        OrderStatusUpdateIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "CONFIRMED" | "PREPARING" | "SHIPPED" | "COMPLETED" | "CANCELLED";
            /** Note */
            note?: string | null;
        };
        /** PaymentOut */
        PaymentOut: {
            /** Method */
            method: string;
            /** Status */
            status: string;
            /** Amount */
            amount: number;
            /** Paid At */
            paid_at: string | null;
        };
        /** ProductCreateIn */
        ProductCreateIn: {
            /** Name */
            name: string;
            /**
             * Product Type
             * @enum {string}
             */
            product_type: "CANDLE" | "CARD" | "COMBO";
            /** Description */
            description: string;
            /** Story */
            story?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Burn Time */
            burn_time?: string | null;
            /** Ingredients */
            ingredients?: string | null;
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /**
             * Allow Custom Scent
             * @default false
             */
            allow_custom_scent: boolean;
            /** Price */
            price?: number | null;
            /**
             * Stock Quantity
             * @default 0
             */
            stock_quantity: number;
            /** Variants */
            variants?: components["schemas"]["VariantCreateIn"][] | null;
            /** Components */
            components?: components["schemas"]["ComponentIn"][] | null;
        };
        /** ProductDetail */
        ProductDetail: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Product Type */
            product_type: string;
            /** Image Url */
            image_url: string | null;
            /** Featured */
            featured: boolean;
            /** Allow Custom Scent */
            allow_custom_scent: boolean;
            /** Price From */
            price_from: number;
            /** In Stock */
            in_stock: boolean;
            /** Description */
            description: string;
            /** Story */
            story: string | null;
            /** Burn Time */
            burn_time: string | null;
            /** Ingredients */
            ingredients: string | null;
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
            /** Components */
            components: components["schemas"]["ComboComponentOut"][];
        };
        /** ProductListItem */
        ProductListItem: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Product Type */
            product_type: string;
            /** Image Url */
            image_url: string | null;
            /** Featured */
            featured: boolean;
            /** Allow Custom Scent */
            allow_custom_scent: boolean;
            /** Price From */
            price_from: number;
            /** In Stock */
            in_stock: boolean;
        };
        /** ProductUpdateIn */
        ProductUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Story */
            story?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Burn Time */
            burn_time?: string | null;
            /** Ingredients */
            ingredients?: string | null;
            /** Featured */
            featured?: boolean | null;
            /** Allow Custom Scent */
            allow_custom_scent?: boolean | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone?: string | null;
        };
        /** ScentCreateIn */
        ScentCreateIn: {
            /** Name Vi */
            name_vi: string;
            /** Name En */
            name_en: string;
            /** Slug */
            slug?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Add To Candles
             * @default true
             */
            add_to_candles: boolean;
            /**
             * Initial Stock
             * @default 0
             */
            initial_stock: number;
        };
        /** ScentOut */
        ScentOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name Vi */
            name_vi: string;
            /** Name En */
            name_en: string;
            /** Description */
            description: string | null;
            /** Notes */
            notes: string | null;
        };
        /** ScentUpdateIn */
        ScentUpdateIn: {
            /** Name Vi */
            name_vi?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** SelectionIn */
        SelectionIn: {
            /** Slot No */
            slot_no: number;
            /** Variant Id */
            variant_id?: number | null;
            /** Custom Scent Text */
            custom_scent_text?: string | null;
        };
        /** ShippingSnapshot */
        ShippingSnapshot: {
            /** Recipient Name */
            recipient_name: string;
            /** Phone */
            phone: string;
            /** Province */
            province: string;
            /** District */
            district: string | null;
            /** Ward */
            ward: string;
            /** Address Line */
            address_line: string;
        };
        /** StockIssue */
        StockIssue: {
            /**
             * Code
             * @enum {string}
             */
            code: "OUT_OF_STOCK" | "INSUFFICIENT_STOCK";
            /** Label */
            label: string;
            /** Available */
            available: number;
        };
        /** TimelineEntry */
        TimelineEntry: {
            /** Status */
            status: string;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantCreateIn */
        VariantCreateIn: {
            /** Scent Id */
            scent_id: number;
            /** Size Ml */
            size_ml: number;
            /** Price */
            price: number;
            /**
             * Stock Quantity
             * @default 0
             */
            stock_quantity: number;
            /** Label */
            label?: string | null;
        };
        /** VariantOut */
        VariantOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Size Ml */
            size_ml: number | null;
            /** Price */
            price: number;
            /** Stock Quantity */
            stock_quantity: number;
            scent: components["schemas"]["ScentOut"] | null;
        };
        /** VariantUpdateIn */
        VariantUpdateIn: {
            /** Price */
            price?: number | null;
            /** Label */
            label?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Stock Quantity */
            stock_quantity?: number | null;
            /** Stock Delta */
            stock_delta?: number | null;
        };
        /** SelectionOut */
        app__schemas__cart__SelectionOut: {
            /** Slot No */
            slot_no: number;
            /** Slot Type */
            slot_type: string;
            /** Variant Id */
            variant_id: number | null;
            /** Scent Name */
            scent_name: string | null;
            /** Is Custom */
            is_custom: boolean;
            /** Custom Scent Text */
            custom_scent_text: string | null;
        };
        /** SelectionOut */
        app__schemas__order__SelectionOut: {
            /** Slot No */
            slot_no: number;
            /** Slot Type */
            slot_type: string;
            /** Scent Name */
            scent_name: string | null;
            /** Is Custom */
            is_custom: boolean;
            /** Custom Scent Text */
            custom_scent_text: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_products_products_get: {
        parameters: {
            query?: {
                type?: string | null;
                q?: string | null;
                featured?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_products__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_login_auth_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_addresses_me_addresses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressOut"][];
                };
            };
        };
    };
    create_address_me_addresses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_address_me_addresses__address_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_address_me_addresses__address_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cart_cart_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
        };
    };
    clear_cart_cart_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
        };
    };
    add_item_cart_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_cart_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_cart_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListItem"][];
                };
            };
        };
    };
    create_order_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_orders__order_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_admin_orders_get: {
        parameters: {
            query?: {
                status?: string | null;
                payment_status?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_admin_orders__order_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_status_admin_orders__order_code__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_custom_scent_admin_custom_scent_requests_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCustomScentListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_custom_scent_admin_custom_scent_requests__request_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomScentReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCustomScentListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_admin_products_get: {
        parameters: {
            query?: {
                type?: string | null;
                q?: string | null;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_admin_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_admin_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_admin_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_admin_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_components_admin_products__product_id__components_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_variant_admin_products__product_id__variants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminVariantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_variant_admin_variants__variant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminVariantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scents_admin_scents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminScentOut"][];
                };
            };
        };
    };
    create_scent_admin_scents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScentCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminScentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scent_admin_scents__scent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scent_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScentUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminScentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_admin_dashboard_get: {
        parameters: {
            query?: {
                days?: number;
                low_stock_threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
