"""order group

Revision ID: 8fd4a0512cde
Revises: e1ae1403420e
Create Date: 2026-10-06 09:04:30.733695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fd4a0512cde'
down_revision: Union[str, Sequence[str], None] = 'e1ae1403420e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('shipping_fee', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('ship_recipient_name', sa.String(length=150), nullable=False),
    sa.Column('ship_phone', sa.String(length=20), nullable=False),
    sa.Column('ship_province', sa.String(length=100), nullable=False),
    sa.Column('ship_district', sa.String(length=100), nullable=True),
    sa.Column('ship_ward', sa.String(length=100), nullable=False),
    sa.Column('ship_address_line', sa.String(length=255), nullable=False),
    sa.Column('source_address_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','CONFIRMED','PREPARING','SHIPPED','COMPLETED','CANCELLED')", name='ck_orders_status'),
    sa.CheckConstraint('subtotal >= 0 AND shipping_fee >= 0 AND total = subtotal + shipping_fee', name='ck_orders_amounts'),
    sa.ForeignKeyConstraint(['source_address_id'], ['shipping_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('variant_label', sa.String(length=200), nullable=False),
    sa.Column('size_ml', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('custom_scent_text', sa.String(length=500), nullable=True),
    sa.CheckConstraint('line_total = unit_price * quantity', name='ck_order_items_line_total'),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','CONFIRMED','PREPARING','SHIPPED','COMPLETED','CANCELLED')", name='ck_order_history_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('order_stock_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_stock_alloc_quantity'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'variant_id', name='uq_stock_alloc_order_variant')
    )
    op.create_index(op.f('ix_order_stock_allocations_order_id'), 'order_stock_allocations', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payos_order_code', sa.BigInteger(), nullable=True),
    sa.Column('payos_payment_link_id', sa.String(length=100), nullable=True),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_webhook', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('PAYOS','COD')", name='ck_payments_method'),
    sa.CheckConstraint("status IN ('PENDING','PAID','FAILED','CANCELLED')", name='ck_payments_status'),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payos_order_code')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('order_item_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.String(length=20), server_default='CANDLE', nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('scent_name', sa.String(length=150), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('custom_scent_text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', 'slot_no', name='uq_order_selection_slot')
    )
    op.create_index(op.f('ix_order_item_selections_order_item_id'), 'order_item_selections', ['order_item_id'], unique=False)
    op.create_table('custom_scent_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('requested_text', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('internal_note', sa.String(length=500), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','ACCEPTED','REJECTED')", name='ck_custom_scent_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selection_id'], ['order_item_selections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', 'selection_id', name='uq_custom_scent_target', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_custom_scent_requests_order_id'), 'custom_scent_requests', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_scent_requests_order_id'), table_name='custom_scent_requests')
    op.drop_table('custom_scent_requests')
    op.drop_index(op.f('ix_order_item_selections_order_item_id'), table_name='order_item_selections')
    op.drop_table('order_item_selections')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_stock_allocations_order_id'), table_name='order_stock_allocations')
    op.drop_table('order_stock_allocations')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
