"""cart group

Revision ID: e1ae1403420e
Revises: 8eae4014384d
Create Date: 2026-10-05 09:29:16.615064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ae1403420e'
down_revision: Union[str, Sequence[str], None] = '8eae4014384d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('size_ml', sa.Integer(), nullable=True),
    sa.Column('custom_scent_text', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity BETWEEN 1 AND 99', name='ck_cart_items_quantity'),
    sa.CheckConstraint('variant_id IS NOT NULL OR (size_ml IS NOT NULL AND custom_scent_text IS NOT NULL)', name='ck_cart_items_target'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_table('cart_item_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_item_id', sa.Integer(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.String(length=20), server_default='CANDLE', nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('custom_scent_text', sa.String(length=500), nullable=True),
    sa.CheckConstraint("slot_type <> 'CANDLE' OR ((variant_id IS NOT NULL AND NOT is_custom) OR (variant_id IS NULL AND is_custom AND custom_scent_text IS NOT NULL))", name='ck_cart_selection_scent'),
    sa.CheckConstraint("slot_type IN ('CANDLE','CARD')", name='ck_cart_selection_type'),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_item_id', 'slot_no', name='uq_cart_selection_slot')
    )
    op.create_index(op.f('ix_cart_item_selections_cart_item_id'), 'cart_item_selections', ['cart_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_item_selections_cart_item_id'), table_name='cart_item_selections')
    op.drop_table('cart_item_selections')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_table('carts')
    # ### end Alembic commands ###
