"""product group

Revision ID: f6418c26b686
Revises: 69f21bdae876
Create Date: 2026-10-05 03:03:36.959236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6418c26b686'
down_revision: Union[str, Sequence[str], None] = '69f21bdae876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('burn_time', sa.String(length=200), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_custom_scent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("product_type IN ('CANDLE','CARD','COMBO')", name='ck_products_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('combo_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combo_product_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=20), nullable=False),
    sa.Column('size_ml', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint("component_type IN ('CANDLE','CARD')", name='ck_components_type'),
    sa.CheckConstraint('quantity > 0', name='ck_components_quantity'),
    sa.ForeignKeyConstraint(['combo_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('scent_id', sa.Integer(), nullable=True),
    sa.Column('size_ml', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_variants_price'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_variants_stock'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scent_id'], ['scents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_ml', 'scent_id', name='uq_variant_product_size_scent', postgresql_nulls_not_distinct=True)
    )
    op.add_column('scents', sa.Column('slug', sa.String(length=50), nullable=False))
    op.add_column('scents', sa.Column('name_vi', sa.String(length=150), nullable=False))
    op.add_column('scents', sa.Column('name_en', sa.String(length=100), nullable=False))
    op.add_column('scents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('scents', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_constraint(op.f('scents_name_key'), 'scents', type_='unique')
    op.create_unique_constraint(None, 'scents', ['slug'])
    op.create_unique_constraint(None, 'scents', ['name_en'])
    op.drop_column('scents', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scents', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'scents', type_='unique')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'scents', type_='unique')
    op.create_unique_constraint(op.f('scents_name_key'), 'scents', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('scents', 'notes')
    op.drop_column('scents', 'description')
    op.drop_column('scents', 'name_en')
    op.drop_column('scents', 'name_vi')
    op.drop_column('scents', 'slug')
    op.drop_table('product_variants')
    op.drop_table('combo_components')
    op.drop_table('products')
    # ### end Alembic commands ###
